config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'category'
      get 'join'
      get 'recomend'
    end
      member do
        post 'room_user'
        delete 'deroom_user'
      
        
      end
  
    
    resources :messages, only: [:index, :create, :new] 

  
  resources :proposes, only: [:create, :destroy] do
    member do
      post 'good'
  end
end
    
      
    

  
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room 
  belongs_to :user
  

  validates :content, presence: true

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.order(id: "DESC")
    @propose = Propose.new
    @proposes = @room.proposes.order(id: "DESC")

    @goods = @propose.goods
    

  
    

    

   
  end


  

  def create
    @room = Room.find(params[:room_id])
    
   
    message = @room.messages.new(message_params)
   
    

    if message.save
      # redirect_to action: :index
      
    render json: {message: message}
    # render json: {sender: sender}
    end
    # if @message.save
    #   redirect_to action: :index
    # else
    #   render :index
    # end


end

private
def message_params
  params.require(:message).permit(:content).merge(user_id: current_user.id)
end





end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<%=  render "shared/header" %>
<div class="messages">
<div class="main-messages">

<div id="list">


<% @messages.each do |message| %>
    <div class="post">
    <div class="post-date">
      投稿日時：<%= message.created_at %>
    </div> 
    <div class="post-content">
      <%= message.content %>
      <%= message.user.nickname%>
    </div>

    <%# <%= image_tag message.image.variant(resize: '200x200'), class: 'message-image' if message.image.attached? %> 
  </div>
<% end %>
</div>
<div class="propose-list">
<% @proposes.each do |propose|%>




<div class="propose">
<div class="propose-title">
タイトル：<%= propose.title %> 
</div>
<div class=propose-concept>
目的：<%= propose.concept %>
</div>
<div class="propose-require">
必要人数：<%= "#{propose.require_people}人" %>
</div>
<div class="propose-info">
提案者:<%= propose.user.nickname%>
</div>
<div class="propose-good">
<%= button_to "参加する", good_room_propose_path(@room.id, propose.id), method: :post %>
参加者:<%= propose.goods.count%>人 
</div>
<div class="propose-join">

参加者リスト:
<% propose.goods.each do |good| %>
 <%=good.user.nickname%>
<% end %>

</div>
</div> 


<% end%>
</div>
</div>



<div class="form-list">
<div class="message-form">
<%= form_with  model: [@room, @message], method: :post, class: 'form', id: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', id: "new-message", placeholder: 'type a message'%>
    <%# <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden', id: 'new-image' %>
    <%# </label> %> 
  <%= f.submit '送信', class: 'form-submit', id: 'submit' %>
  </div>
<% end %>
</div>

<div class="message-propose">
<%= form_with url: room_proposes_path(@room.id), method: :post, class: 'form', id: 'propose-form', local: true do |f|%>
<div class="form-input">
<%= f.text_field :title, class: 'form-title', id: 'new-propose', placeholder: 'タイトルを入力してください'%>
<%= f.text_field :concept, class: 'form-concept', id: 'new-concept', placeholder: '目的を入力してください'%>
<%= f.number_field :require_people, in: 1..20, class: 'form-require', id: 'new-require', placeholder:'必要最低人数を入力してください'%>

<%= f.submit '作成する', class: "propose-submit", id: "propose-submit"%>
<% end %>
</div>
</div>
<% unless @room.users.exists?(id: current_user.id)%>
<%= button_to "所属する", room_user_room_path(@room.id), method: :post %>
<% else %>
<%= button_to "脱退する", deroom_user_room_path(@room.id), method: :delete %>
<%end %>
</div>