config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'category'
      get 'join'
      get 'recomend'
    end
      member do
        post 'room_user'
        delete 'deroom_user'
      
        
      end
  
    
    resources :messages, only: [:index, :create, :new] 

  
  resources :proposes, only: [:create, :destroy] do
    member do
      post 'good'
  end
end
    
      
    

  
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
<div class="footer-content">
hobby chat
</div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
<div class="heading">
<h1 class="logo"><a href="/">HOBBY CHAT</a><h1>
</div>
<div class="navber">
 <ul class="nav-list">
 <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "ルームを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
  <li class="category-menu" id="category-menu">カテゴリー
  <ul class="category-lists hidden" id="category-pull-down">
  <li><%=link_to 'ボードゲーム', category_rooms_path(category_id: 2)%></li>
  <li><%=link_to 'デジタルゲーム',category_rooms_path(category_id: 3)%></li>
  <li><%=link_to 'コミック',category_rooms_path(category_id: 4)%></li>
  <li><%=link_to '映画',category_rooms_path(category_id: 5)%></li>
  <li><%=link_to 'スポーツ',category_rooms_path(category_id: 6)%></li>
  <li><%=link_to 'ギャンブル',category_rooms_path(category_id: 7)%></li>
  <li><%=link_to 'その他',category_rooms_path(category_id: 8)%></li>
  </li>
  </ul>
 
  <% unless user_signed_in?%>
  <li><%= link_to 'ログイン', new_user_session_path, class: "sign-in"%></li>
  <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up"%></li>
  <% else%>
   <li><%= link_to '新規ルーム作成', new_room_path, class: "create-room"%></li>
  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sign-out"%></li>
  <% end %>
</ul>
</div>


</header>