config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'category'
      get 'join'
      get 'recomend'
    end
      member do
        post 'room_user'
        delete 'deroom_user'
      
        
      end
  
    
    resources :messages, only: [:index, :create, :new] 

  
  resources :proposes, only: [:create, :destroy] do
    member do
      post 'good'
  end
end
    
      
    

  
  end
end

app/models/room.rb
class Room < ApplicationRecord
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
  belongs_to_active_hash :category
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
  has_many :room_tags
  has_many :tags, through: :room_tags
  has_many :proposes

  def self.category(category_id)
  Room.where(category_id: category_id)
end
  def self.search(search)
    if search != nil
      Room.where('room_name LIKE(?) or concept LIKE(?)' , "%#{search}%",  "%#{search}%")
    else
      Room.All
    end
  end
end

app/models/room_form.rb
class RoomForm
  include ActiveModel::Model
  attr_accessor :room_name, :concept, :category_id, :area_id, :tag_name, :user_id
  with_options presence: true do
    validates :room_name
    validates :concept
    validates :category_id
    validates :area_id
    validates :tag_name
  end
  def save
    @room = Room.create(room_name: room_name, concept: concept, category_id: category_id, area_id: area_id, user_id: user_id)
    @tag = Tag.where(tag_name: tag_name).first_or_initialize
    @tag.save
    RoomTag.create(room_id: @room.id, tag_id: @tag.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms =Room.all
  end
  def new
    @room_form = RoomForm.new
  end
  def show
    room_user = RoomUser.find_by(user_id: current_user.id)
    @rooms = Room.find_by(room_id: room_user.room_id)
  end
  def join
    join_user = RoomUser.where(user_id: current_user.id).pluck(:room_id)
    @rooms = Room.where(id: join_user)
   end
   def recomend
    aa = Room.where(category_id: current_user.category.id).pluck(:category_id)
    @rooms = Room.where(id: aa)
    
    
   end
  def category
    @rooms = Room.category(params[:category_id])
  end
  def search
    if (params[:keyword]) == '#'
      @rooms = Tag.search(params[:keyword]).order('created_at DESC')
    else
      @rooms = Room.search(params[:keyword]).order('created_at DESC')
    end
  end
  def room_user
    # @room = Room.find(params[:id])
    # RoomUser.create(room_params)
    # redirect_to action: :index
    # end
    
      @room = Room.find(params[:id])
      user = User.find(current_user.id)
      @room.users << current_user
      redirect_to room_messages_path(@room.id)
  end
  def deroom_user
    @room = Room.find(params[:id])
    user = current_user
    
    room_user = RoomUser.find_by(user_id: user.id, room_id: @room.id)
    room_user.delete
    redirect_to room_messages_path(@room.id)
  end
  
  def create
    @room_form = RoomForm.new(room_form_params)
    if @room_form.valid?
      @room_form.save
      redirect_to root_path
    else
      render :new
    end
  end

 

  private
  def room_form_params
    params.require(:room_form).permit(:room_name, :concept, :category_id, :area_id, :tag_name).merge(user_id: current_user.id)
  end
  
  # def good_params
  #   params.merge(propose_id: @propose.id, user_id: current_user.id)
  # end
  
 
  # def room_params
  #   params.require(:room).merge(user_id: current_user.id, room_id: params[:room_id])
  # end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/category.html.erb
<%=  render "shared/header" %>
<div class="rooms-show">
<div class="room-show">
<a>ルーム一覧</a>
</div>
<div class="rooms">
<% @rooms.each do |room|%>
<%= link_to  room_messages_path(room.id), class:"rooms-list" do  %>
<div class="rooms-info">

<div class="room-info">
ルーム名：<%=  room.room_name  %>
</div>
<div class="room-info">
コンセプト：<%= room.concept%>
</div>
<div class="room-info">
カテゴリー名：<%= room.category.name%>
</div>
<div class="room-info">
県名：<%= room.area.name%><br>
</div>
<div class="room-info">
所属人数:<%= room.room_users.count + 1%>人
</div>
</div>
<% end%>
<% end%>
<div>
</div>

app/views/rooms/index.html.erb
<%=  render "shared/header" %>
<div class="content-main">
<div class="content-list">
<div class="content-top">
<div class="category"><%= link_to image_tag("igo.jpeg" ), category_rooms_path(category_id: 2) %><p>ボードゲーム</p></div> 
<div class="category"><%= link_to image_tag("game.png" ),category_rooms_path(category_id: 3) %><p>デジタルゲーム</p> </div>
<div class="category"><%= link_to image_tag("comic.jpeg" ), category_rooms_path(category_id: 4) %><p>コミック<p></div>
</div>
<div class="content-center"> 
<div class="category"><%= link_to image_tag("movie.jpeg" ), category_rooms_path(category_id: 5) %><p>映画</p></div> 
<div class="category"><%= link_to image_tag("sport.jpeg" ), category_rooms_path(category_id: 6) %><p>スポーツ</p> </div>
<div class="category"><%= link_to image_tag("gamble.jpeg" ),category_rooms_path(category_id: 7) %><p>ギャンブル</p> </div>
</div>
<div class="content-bottom">
<div class="category"><%= link_to image_tag("etc.jpeg" ),category_rooms_path(category_id: 8) %><p>その他</p> </div>
<% if user_signed_in?%>
<div class="category">
<%= link_to image_tag("join.jpeg" ), join_rooms_path %><p>所属ルーム</p>

</div>
<div class="category"> 
<%= link_to image_tag("recomend.jpeg" ), recomend_rooms_path %><p>オススメ</p>



</div>
<% end %>
</div>



</div>
</div>


<%= render "shared/footer"%>

app/views/rooms/join.html.erb
<%=  render "shared/header" %>
<div class="rooms-show">
<div class="room-show">
<a>ルーム一覧</a>
</div>
<div class="rooms">
<% @rooms.each do |room|%>
<%= link_to  room_messages_path(room.id), class:"rooms-list" do  %>
<div class="rooms-info">

<div class="room-info">
ルーム名：<%=  room.room_name  %>
</div>
<div class="room-info">
コンセプト：<%= room.concept%>
</div>
<div class="room-info">
カテゴリー名：<%= room.category.name%>
</div>
<div class="room-info">
県名：<%= room.area.name%><br>
</div>
<div class="room-info">
所属人数:<%= room.room_users.count + 1%>人
</div>
</div>
<% end%>
<% end%>
<div>
</div>

app/views/rooms/new.html.erb
<%= render "shared/header"%>
<div class="new-main">
<div class="new-list">
<%= form_with model: @room_form, url: rooms_path, method: :post,  local: true do |f|%>
<%= render 'shared/error_messages', model: f.object %>
<div class="new-form">
<div class="new-content"><h1>ルーム名</h1><%= f.text_area :room_name, class:"room-name", id:"room-name", placeholder:"ルーム名"%></div>
<div class="new-content"><h1>コンセプト</h1><%= f.text_area :concept, class:"room-concept", id:"room-concept",placeholder:"コンセプト"%></div>
<div class="new-content"><h1>タグ</h1><%= f.text_area :tag_name, class: "room-tag", id: "room-tag", placeholder: "タグ名"%></div>
<div class="new-content"><h1>エリア</h1><%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"room-category"}) %></div>
<div class="new-content"><h1>カテゴリー</h1><%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"room-category"}) %></div>
<div class="new-content"><%= f.submit "作成する" ,class:"sell-btn" %><div>
</div>
<%end%>
</div>
</div>

app/views/rooms/recomend.html.erb
<%=  render "shared/header" %>
<div class="rooms-show">
<div class="room-show">
<a>ルーム一覧</a>
</div>
<div class="rooms">
<% @rooms.each do |room|%>
<%= link_to  room_messages_path(room.id), class:"rooms-list" do  %>
<div class="rooms-info">

<div class="room-info">
ルーム名：<%=  room.room_name  %>
</div>
<div class="room-info">
コンセプト：<%= room.concept%>
</div>
<div class="room-info">
カテゴリー名：<%= room.category.name%>
</div>
<div class="room-info">
県名：<%= room.area.name%><br>
</div>
<div class="room-info">
所属人数:<%= room.room_users.count + 1%>人
</div>
</div>
<% end%>
<% end%>
<div>
</div>

app/views/rooms/search.html.erb
<%=  render "shared/header" %>
<div class="rooms-show">
<div class="room-show">
<a>ルーム一覧</a>
</div>
<div class="rooms">
<% @rooms.each do |room|%>
<div class="rooms-info">
<div class="room-info">
ルーム名：<%= link_to room.room_name, room_messages_path(room.id), class: "link"  %>
</div>
<div class="room-info">
コンセプト：<%= room.concept%>
</div>
<div class="room-info">
カテゴリー名：<%= room.category.name%>
</div>
<div class="room-info">
県名：<%= room.area.name%><br>
</div>
</div>
<% end%>
</div>
</div>

app/views/rooms/show.html.erb
<%=  render "shared/header" %>
<div class="rooms-show">
<div class="room-show">
<a>ルーム一覧</a>
</div>
<div class="rooms">
<% @rooms.each do |room|%>
<%= link_to  room_messages_path(room.id), class:"rooms-list" do  %>
<div class="rooms-info">

<div class="room-info">
ルーム名：<%=  room.room_name  %>
</div>
<div class="room-info">
コンセプト：<%= room.concept%>
</div>
<div class="room-info">
カテゴリー名：<%= room.category.name%>
</div>
<div class="room-info">
県名：<%= room.area.name%><br>
</div>
<div class="room-info">
所属人数:<%= room.room_users.count + 1%>人
</div>
</div>
<% end%>
<% end%>
<div>
</div>